input:
  sql_select:
    driver: postgres
    dsn: postgres://postgres:password@localhost:5436/postgres?sslmode=disable
    table: users
    columns:
      [
        id,
        first_name,
        last_name,
        street_address,
        city,
        state,
        zipcode,
        loyalty_plan,
        price,
      ]
pipeline:
  processors:
    - bloblang: |
        root.id = this.id
        root.first_name = this.first_name
        root.last_name = this.last_name
        root.street_address = this.street_address
        root.city = this.city
        root.state = this.state
        root.zipcode = this.zipcode
        root.loyalty_plan = this.loyalty_plan
        root.price = this.price
output:
  sql_insert:
    driver: postgres
    dsn: postgres://postgres:password@localhost:5437/postgres?sslmode=disable
    table: users
    columns:
      [
        id,
        first_name,
        last_name,
        street_address,
        city,
        state,
        zipcode,
        loyalty_plan,
        price,
      ]
    args_mapping: |
      root = [
        this.id,
        this.first_name,
        this.last_name,
        this.street_address,
        this.city,
        this.state,
        this.zipcode,
        this.loyalty_plan,
        this.price
        ]
